function long_format = import_mturk_data(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   UNTITLED = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   UNTITLED = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Untitled = importfile('12.02.2020_trial.csv', 2, 4168);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/02/12 17:16:02

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,6,11,13,14,17,18,26,27,35]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,2,6,11,13,14,17,18,26,27,35]);
rawStringColumns = string(raw(:, [3,4,5,7,8,9,10,12,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,36,37,38,39,40,41]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
long_format = table;
long_format.subjnum = cell2mat(rawNumericColumns(:, 1));
long_format.exp_version = cell2mat(rawNumericColumns(:, 2));
long_format.worker_ID = categorical(rawStringColumns(:, 1));
long_format.assignment_ID = categorical(rawStringColumns(:, 2));
long_format.hit_ID = categorical(rawStringColumns(:, 3));
long_format.rt = cell2mat(rawNumericColumns(:, 3));
long_format.response = categorical(rawStringColumns(:, 4));
long_format.task = categorical(rawStringColumns(:, 5));
long_format.tasknum = categorical(rawStringColumns(:, 6));
long_format.task_displayed = categorical(rawStringColumns(:, 7));
long_format.key_press = cell2mat(rawNumericColumns(:, 4));
long_format.correct = categorical(rawStringColumns(:, 8));
long_format.correct_key = cell2mat(rawNumericColumns(:, 5));
long_format.stimnum = cell2mat(rawNumericColumns(:, 6));
long_format.success = categorical(rawStringColumns(:, 9));
long_format.trial_type = categorical(rawStringColumns(:, 10));
long_format.trial_index = cell2mat(rawNumericColumns(:, 7));
long_format.time_elapsed = cell2mat(rawNumericColumns(:, 8));
long_format.BDMquizgrade = categorical(rawStringColumns(:, 11));
long_format.slider_start = categorical(rawStringColumns(:, 12));
long_format.TOT = categorical(rawStringColumns(:, 13));
long_format.nback = categorical(rawStringColumns(:, 14));
long_format.n = categorical(rawStringColumns(:, 15));
long_format.detect = categorical(rawStringColumns(:, 16));
long_format.switch1 = categorical(rawStringColumns(:, 17));
long_format.prob_switch = cell2mat(rawNumericColumns(:, 9));
long_format.rule = cell2mat(rawNumericColumns(:, 10));
long_format.total_points = categorical(rawStringColumns(:, 18));
long_format.overall = categorical(rawStringColumns(:, 19));
long_format.perf = categorical(rawStringColumns(:, 20));
long_format.points = categorical(rawStringColumns(:, 21));
long_format.value = categorical(rawStringColumns(:, 22));
long_format.offer = categorical(rawStringColumns(:, 23));
long_format.practice = categorical(rawStringColumns(:, 24));
long_format.practice_accuracy = cell2mat(rawNumericColumns(:, 11));
long_format.number_practice_hard = categorical(rawStringColumns(:, 25));
long_format.n_switch_rule_sides = categorical(rawStringColumns(:, 26));
long_format.responses = categorical(rawStringColumns(:, 27));
long_format.VarName39 = rawStringColumns(:, 28);
long_format.VarName40 = rawStringColumns(:, 29);
long_format.VarName41 = rawStringColumns(:, 30);

