function Pilot5 = import_subj5_txt(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   PILOT5 = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   PILOT5 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Pilot5 = importfile('Pilot5.txt', 2, 245);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/11/13 18:03:08

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[3,4,6,7,10,11,12,13,14,16,17]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [3,4,6,7,10,11,12,13,14,16,17]);
rawStringColumns = string(raw(:, [1,2,5,8,9,15,18,19,20,21,22,23]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [2,4,5,6]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
Pilot5 = table;
Pilot5.success = rawStringColumns(:, 1);
Pilot5.trial_type = categorical(rawStringColumns(:, 2));
Pilot5.trial_index = cell2mat(rawNumericColumns(:, 1));
Pilot5.time_elapsed = cell2mat(rawNumericColumns(:, 2));
Pilot5.internal_node_id = rawStringColumns(:, 3);
Pilot5.rt = cell2mat(rawNumericColumns(:, 3));
Pilot5.response = cell2mat(rawNumericColumns(:, 4));
Pilot5.stimulus = categorical(rawStringColumns(:, 4));
Pilot5.task = categorical(rawStringColumns(:, 5));
Pilot5.tasknum = cell2mat(rawNumericColumns(:, 5));
Pilot5.slider_start = cell2mat(rawNumericColumns(:, 6));
Pilot5.key_press = cell2mat(rawNumericColumns(:, 7));
Pilot5.nback = cell2mat(rawNumericColumns(:, 8));
Pilot5.correct_key = cell2mat(rawNumericColumns(:, 9));
Pilot5.detect = categorical(rawStringColumns(:, 6));
Pilot5.n = cell2mat(rawNumericColumns(:, 10));
Pilot5.stimnum = cell2mat(rawNumericColumns(:, 11));
Pilot5.TOT = rawStringColumns(:, 7);
Pilot5.overall = rawStringColumns(:, 8);
Pilot5.performance_by_block = rawStringColumns(:, 9);
Pilot5.points_list = rawStringColumns(:, 10);
Pilot5.value_list = rawStringColumns(:, 11);
Pilot5.offer_list = rawStringColumns(:, 12);

